[2024-09-03T02:10:43.541+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T02:10:43.561+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T02:10:43.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T02:10:43.571+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-03T02:10:43.591+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrear_datos_API> on 2024-09-02 00:00:00+00:00
[2024-09-03T02:10:43.602+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T02:10:43.625+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-09-03T02:10:43.639+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'redshift_etl_dag', 'extrear_datos_API', 'scheduled__2024-09-02T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpnhoqpn3v']
[2024-09-03T02:10:43.655+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask extrear_datos_API
[2024-09-03T02:10:43.775+0000] {task_command.py:426} INFO - Running <TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [running]> on host d6a54f99c9c8
[2024-09-03T02:10:43.938+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose_araya' AIRFLOW_CTX_DAG_ID='redshift_etl_dag' AIRFLOW_CTX_TASK_ID='extrear_datos_API' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-02T00:00:00+00:00'
[2024-09-03T02:10:43.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T02:10:43.963+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T02:10:43.964+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: API.getdata() missing 1 required positional argument: 'self'
[2024-09-03T02:10:43.977+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=redshift_etl_dag, task_id=extrear_datos_API, run_id=scheduled__2024-09-02T00:00:00+00:00, execution_date=20240902T000000, start_date=20240903T021043, end_date=20240903T021043
[2024-09-03T02:10:43.993+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task extrear_datos_API (API.getdata() missing 1 required positional argument: 'self'; 75)
[2024-09-03T02:10:44.011+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-03T02:10:44.037+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T02:10:44.040+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-03T14:11:23.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T14:11:23.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T14:11:23.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T14:11:23.196+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-03T14:11:23.210+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrear_datos_API> on 2024-09-02 00:00:00+00:00
[2024-09-03T14:11:23.217+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T14:11:23.219+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-09-03T14:11:23.218+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'redshift_etl_dag', 'extrear_datos_API', 'scheduled__2024-09-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpubvsqh90']
[2024-09-03T14:11:23.221+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extrear_datos_API
[2024-09-03T14:11:23.266+0000] {task_command.py:426} INFO - Running <TaskInstance: redshift_etl_dag.extrear_datos_API scheduled__2024-09-02T00:00:00+00:00 [running]> on host cd927b53650d
[2024-09-03T14:11:23.338+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jose_araya' AIRFLOW_CTX_DAG_ID='redshift_etl_dag' AIRFLOW_CTX_TASK_ID='extrear_datos_API' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-02T00:00:00+00:00'
[2024-09-03T14:11:23.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T14:11:29.843+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-03T14:11:29.844+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T14:11:29.852+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=redshift_etl_dag, task_id=extrear_datos_API, run_id=scheduled__2024-09-02T00:00:00+00:00, execution_date=20240902T000000, start_date=20240903T141123, end_date=20240903T141129
[2024-09-03T14:11:29.873+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-03T14:11:29.887+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-03T14:11:29.890+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
